<QuestDetailScreen>:
    orientation: "vertical"
    Label:
        text: root.quest_name
        font_size: '24sp'
        size_hint_y: None
        height: self.texture_size[1] + dp(10)
    ScrollView:
        GridLayout:
            id: objectives_container
            cols: 1
            size_hint_y: None
            height: self.minimum_height
            padding: dp(10)
            spacing: dp(5)
