[mypy]
strict = True
namespace_packages = True
explicit_package_bases = True
files = src
mypy_path = $MYPY_CONFIG_FILE_DIR/src/
exclude = src/ui

[mypy-ui.*]
follow_imports = skip

[mypy-__future__.*]
ignore_missing_imports = True

[mypy-kivymd.*]
ignore_missing_imports = True

[mypy-kivy.*]
ignore_missing_imports = True